# Crash Course General Introduction

## Numpy

In [1]:
import numpy as np

Convert python list into numpy array

In [2]:
mylist = [1, 2, 3, 4]
np.array(mylist)
type(mylist)
type(mylist)

list

In [3]:
mylist

[1, 2, 3, 4]

In [4]:
arr = np.array(mylist)
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a = np.arange(0, 10, 2)
a

array([0, 2, 4, 6, 8])

In [8]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.zeros((1, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.zeros((2, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
type(1.)

float

numpy like to generate or convert to float numbers

In [13]:
np.random.randint(0, 100)

10

In [14]:
np.random.randint(0, 100, (5,5))

array([[82,  7, 75, 28, 75],
       [ 9, 75, 71, 67, 98],
       [ 6, 50, 63, 77, 85],
       [18, 98, 22,  3,  0],
       [60, 27, 31, 58, 59]])

In [15]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
np.linspace(0, 10, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [17]:
np.linspace(0, 10, 201)

array([ 0.  ,  0.05,  0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,
        0.45,  0.5 ,  0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,
        0.9 ,  0.95,  1.  ,  1.05,  1.1 ,  1.15,  1.2 ,  1.25,  1.3 ,
        1.35,  1.4 ,  1.45,  1.5 ,  1.55,  1.6 ,  1.65,  1.7 ,  1.75,
        1.8 ,  1.85,  1.9 ,  1.95,  2.  ,  2.05,  2.1 ,  2.15,  2.2 ,
        2.25,  2.3 ,  2.35,  2.4 ,  2.45,  2.5 ,  2.55,  2.6 ,  2.65,
        2.7 ,  2.75,  2.8 ,  2.85,  2.9 ,  2.95,  3.  ,  3.05,  3.1 ,
        3.15,  3.2 ,  3.25,  3.3 ,  3.35,  3.4 ,  3.45,  3.5 ,  3.55,
        3.6 ,  3.65,  3.7 ,  3.75,  3.8 ,  3.85,  3.9 ,  3.95,  4.  ,
        4.05,  4.1 ,  4.15,  4.2 ,  4.25,  4.3 ,  4.35,  4.4 ,  4.45,
        4.5 ,  4.55,  4.6 ,  4.65,  4.7 ,  4.75,  4.8 ,  4.85,  4.9 ,
        4.95,  5.  ,  5.05,  5.1 ,  5.15,  5.2 ,  5.25,  5.3 ,  5.35,
        5.4 ,  5.45,  5.5 ,  5.55,  5.6 ,  5.65,  5.7 ,  5.75,  5.8 ,
        5.85,  5.9 ,  5.95,  6.  ,  6.05,  6.1 ,  6.15,  6.2 ,  6.25,
        6.3 ,  6.35,  6.4 ,  6.45,  6.5 ,  6.55,  6.6 ,  6.65,  6.7 ,
        6.75,  6.8 ,  6.85,  6.9 ,  6.95,  7.  ,  7.05,  7.1 ,  7.15,
        7.2 ,  7.25,  7.3 ,  7.35,  7.4 ,  7.45,  7.5 ,  7.55,  7.6 ,
        7.65,  7.7 ,  7.75,  7.8 ,  7.85,  7.9 ,  7.95,  8.  ,  8.05,
        8.1 ,  8.15,  8.2 ,  8.25,  8.3 ,  8.35,  8.4 ,  8.45,  8.5 ,
        8.55,  8.6 ,  8.65,  8.7 ,  8.75,  8.8 ,  8.85,  8.9 ,  8.95,
        9.  ,  9.05,  9.1 ,  9.15,  9.2 ,  9.25,  9.3 ,  9.35,  9.4 ,
        9.45,  9.5 ,  9.55,  9.6 ,  9.65,  9.7 ,  9.75,  9.8 ,  9.85,
        9.9 ,  9.95, 10.  ])

In [18]:
np.random.seed(101)

In [19]:
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [20]:
arr = np.random.randint(0, 100, 10)
arr

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [21]:
arr.max()

93

In [22]:
arr.min()

4

In [23]:
arr.min

In [24]:
arr.mean()

47.3

Index location of maximum value

In [25]:
arr.argmax()

8

In [26]:
arr.argmin()

0

In [27]:
arr.reshape(2, 5)

array([[ 4, 63, 40, 60, 92],
       [64,  5, 12, 93, 40]])

In [28]:
mat = np.arange(0, 100).reshape(10, 10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [29]:
mat[5, 2]

52

In [30]:
mat[:, 2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [31]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [32]:
mat[mat > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## Exercises

TASK 1: Import pandas and numpy

In [33]:
import pandas as pd
import numpy as np

TASK 2: Set Numpy's random number generator seed to 101

In [34]:
np.random.seed(101)

TASK 3: Create a NumPy Matrix of 100 rows by 5 columns consisting of random integers from 1-100. (Keep in mind that the upper limit may be exclusive.)

In [35]:
#np.arange(0, 100).reshape(10, 10)
#np.random.randint(0, 100, 10)
mat = np.random.randint(1, 101, (100, 5))
mat

array([[ 96,  12,  82,  71,  64],
       [ 88,  76,  10,  78,  41],
       [  5,  64,  41,  61,  93],
       [ 65,   6,  13,  94,  41],
       [ 50,  84,   9,  30,  60],
       [ 35,  45,  73,  20,  11],
       [ 77,  96,  88,   1,  74],
       [  9,  63,  37,  84, 100],
       [ 29,  64,   8,  11,  53],
       [ 57,  39,  74,  53,  19],
       [ 72,  16,  45,   1,  13],
       [ 18,  76,  80,  98,  94],
       [ 25,  37,  64,  20,  36],
       [ 31,  11,  61,  21,  28],
       [  9,  87,  27,  88,  47],
       [ 48,  55,  87,  10,  46],
       [  3,  19,  59,  93,  12],
       [ 11,  95,  36,  29,   4],
       [ 84,  85,  48,  15,  70],
       [ 61,  70,  52,   7,  89],
       [ 72,  69,  24,  36,  80],
       [ 99,  68,  83,  58,  78],
       [ 47,   4,  47,  30,  87],
       [ 22,  22,  82,  24,  95],
       [ 72,  21,  28,  76,   6],
       [ 50,  87,  90,  64,  83],
       [ 78,   4,  57,  15,  50],
       [ 88,  53,  14,  48,  50],
       [ 25,  21,  65,  53,  61],
       [ 48,  30,  61,  54,  12],
       [ 41,  92,  46,  98,  25],
       [ 37,  39,  10,  53,  68],
       [ 44,   2,  80,  69,  69],
       [ 62,  19,  52,  15,  29],
       [ 18,  88,  47,  53,  17],
       [ 71,  72,  85,  11,  63],
       [ 97,  58,  24,  87,  86],
       [ 27,  77,  67,  55,  18],
       [ 66,  58,  90,   3,  81],
       [ 51,  67,  89,  80,  94],
       [  7,  93,  43,  23,  21],
       [ 26,  98,  55,  72,  73],
       [ 81,  94,  65,  64,  81],
       [ 39,  46,  36,  26,  96],
       [ 76,  73,  12,  77,  80],
       [ 51,  23,  60,  67,   2],
       [ 35,  38,  58,  36,  43],
       [ 45,  50,  32,  80,  86],
       [  4,  56,  74,  94,  95],
       [100,  41,  55,  89,  95],
       [ 87,  18,  69,  18,  19],
       [ 61,  84,  83,   8,  68],
       [ 35,  77,  95,  21,  70],
       [ 74,  60,  35,  70,  26],
       [ 79,  93,  75,  76,  34],
       [ 10,  44,  21,  83,  31],
       [  4,  47,  30,  48,  28],
       [ 82,  72,  26,  95,  58],
       [ 22,  30,   7,  55,  48],
       [ 48,  61,   7,  76,  98],
       [ 54,  45,  99,  40,  33],
       [ 88,  79,  22,  91,  15],
       [ 21,   2,  71,  26,  46],
       [ 97,  33,  32,  42,  80],
       [ 88,  23,  95,  47,  72],
       [ 25,  42,  37,  32,  17],
       [ 88,  23,  97,   4,  13],
       [ 72,  10,  88,  96,  40],
       [ 65,  63,  89,  77,  94],
       [ 84,  96,  69,  70,  60],
       [ 53,   8,  41,  74,  87],
       [ 15,  50,  98,  26,  58],
       [ 41,  18,  33,  84,  98],
       [ 28,  48,  14,  71,  16],
       [ 93,  19,  95,  49,  66],
       [ 83,  35,   6,  47,  84],
       [ 28,  27,  21,  88,  85],
       [ 18,  60,  65,  45,   5],
       [ 52,  50,  75,  83,  38],
       [ 54,  94,  74,   6,  38],
       [ 57,  36,  16,  41,  43],
       [ 72,  38,  47,  72,  92],
       [ 98,  37,  44,  28,  67],
       [ 58,   4,  56,  71,  42],
       [ 68,  73,  89,  68,  76],
       [ 70,  93,  21,  16,  58],
       [ 10,  70,  98,  92,  52],
       [ 55,  46,  39,  16,  43],
       [ 62,   9,   4,  89,  73],
       [ 42,  25,  94,  29,  96],
       [ 44,  49,  70,  43,  67],
       [ 83,  67,  89,  79,  15],
       [ 54,  47,  15,  28,  69],
       [ 22,  39,  43,  31,  89],
       [ 80,  57,  66,  94,  38],
       [ 88,  67,  17,  61,  26],
       [100,  31,  42,  73,  46],
       [ 27,  88,  66,  61,  90],
       [ 71,  34,  60,  29,  17],
       [ 50,  96,  42,  12,  87]])

In [36]:
np.size(mat)

500

TASK 4: Now use pd.DataFrame() to read in this numpy array as a dataframe. Simple pass in the numpy array into that function to get back a dataframe. Pandas will auto label the columns to 0-4

In [37]:
df = pd.DataFrame(mat)
df

      0   1   2   3    4
0    96  12  82  71   64
1    88  76  10  78   41
2     5  64  41  61   93
3    65   6  13  94   41
4    50  84   9  30   60
5    35  45  73  20   11
6    77  96  88   1   74
7     9  63  37  84  100
8    29  64   8  11   53
9    57  39  74  53   19
10   72  16  45   1   13
11   18  76  80  98   94
12   25  37  64  20   36
13   31  11  61  21   28
14    9  87  27  88   47
15   48  55  87  10   46
16    3  19  59  93   12
17   11  95  36  29    4
18   84  85  48  15   70
19   61  70  52   7   89
20   72  69  24  36   80
21   99  68  83  58   78
22   47   4  47  30   87
23   22  22  82  24   95
24   72  21  28  76    6
25   50  87  90  64   83
26   78   4  57  15   50
27   88  53  14  48   50
28   25  21  65  53   61
29   48  30  61  54   12
..  ...  ..  ..  ..  ...
70   53   8  41  74   87
71   15  50  98  26   58
72   41  18  33  84   98
73   28  48  14  71   16
74   93  19  95  49   66
75   83  35   6  47   84
76   28  27  21  88   85
77   18  60  65  45    5
78   52  50  75  83   38
79   54  94  74   6   38
80   57  36  16  41   43
81   72  38  47  72   92
82   98  37  44  28   67
83   58   4  56  71   42
84   68  73  89  68   76
85   70  93  21  16   58
86   10  70  98  92   52
87   55  46  39  16   43
88   62   9   4  89   73
89   42  25  94  29   96
90   44  49  70  43   67
91   83  67  89  79   15
92   54  47  15  28   69
93   22  39  43  31   89
94   80  57  66  94   38
95   88  67  17  61   26
96  100  31  42  73   46
97   27  88  66  61   90
98   71  34  60  29   17
99   50  96  42  12   87

[100 rows x 5 columns]

TASK 5: Using your previously created DataFrame, use [df.columns = [...]] (https://stackoverflow.com/questions/11346283/renaming-columns-in-pandas) to rename the pandas columns to be ['f1','f2','f3','f4','label'].

In [38]:
df.rename(columns={0: 'f1', 1: 'f2', 2: 'f3', 3: 'f4', 4: 'label'}, inplace= True)
df

     f1  f2  f3  f4  label
0    96  12  82  71     64
1    88  76  10  78     41
2     5  64  41  61     93
3    65   6  13  94     41
4    50  84   9  30     60
5    35  45  73  20     11
6    77  96  88   1     74
7     9  63  37  84    100
8    29  64   8  11     53
9    57  39  74  53     19
10   72  16  45   1     13
11   18  76  80  98     94
12   25  37  64  20     36
13   31  11  61  21     28
14    9  87  27  88     47
15   48  55  87  10     46
16    3  19  59  93     12
17   11  95  36  29      4
18   84  85  48  15     70
19   61  70  52   7     89
20   72  69  24  36     80
21   99  68  83  58     78
22   47   4  47  30     87
23   22  22  82  24     95
24   72  21  28  76      6
25   50  87  90  64     83
26   78   4  57  15     50
27   88  53  14  48     50
28   25  21  65  53     61
29   48  30  61  54     12
..  ...  ..  ..  ..    ...
70   53   8  41  74     87
71   15  50  98  26     58
72   41  18  33  84     98
73   28  48  14  71     16
74   93  19  95  49     66
75   83  35   6  47     84
76   28  27  21  88     85
77   18  60  65  45      5
78   52  50  75  83     38
79   54  94  74   6     38
80   57  36  16  41     43
81   72  38  47  72     92
82   98  37  44  28     67
83   58   4  56  71     42
84   68  73  89  68     76
85   70  93  21  16     58
86   10  70  98  92     52
87   55  46  39  16     43
88   62   9   4  89     73
89   42  25  94  29     96
90   44  49  70  43     67
91   83  67  89  79     15
92   54  47  15  28     69
93   22  39  43  31     89
94   80  57  66  94     38
95   88  67  17  61     26
96  100  31  42  73     46
97   27  88  66  61     90
98   71  34  60  29     17
99   50  96  42  12     87

[100 rows x 5 columns]

TASK 6: Alright, all the other tasks were hopefully straightforward.
This final task will allow you to quickly check to see if you are at the right level with pandas! Do the following:
- Create a dataframe with the columns ['A','B','C','D'] with each column having 50 rows of random numbers for data. 
- The random numbers should be between 0 and 100. (Hint: Use numpy to create the numbers, then pass it in to pd.DataFrame(), check out the data= and index= parameters for that call.)

In [39]:
#mat = np.random.randint(1, 101, 10*5).reshape(10, 5)
new_df = pd.DataFrame(np.random.randint(0, 101, (50, 4)) , columns= ['A','B','C','D'])
new_df

     A   B   C   D
0   15  95  91  19
1   69   1  77  63
2   87  28  70   5
3    3  12  62  26
4   96  61  87  74
5   99  97  64  95
6    3  88  59  38
7   29  31  88  57
8    9  62  31  13
9   35  47   2  17
10  50  22  30  36
11  22  97  51  38
12  28   4   0  12
13  90   2   7  44
14  54  49  76  98
15   3  32  91  43
16   7  42  66   9
17   5  26  66  22
18  47  27  46  14
19  52  74  54   3
20  94  36  63  41
21  18  37  45  82
22  47  66  97  20
23   9  87  40  13
24  95  16  38  87
25  72  60  78  53
26  48  83  90  41
27  84  78  55  70
28  93  57  86  67
29   8  47  70  39
30  53   5  40  88
31  58  12  70   5
32  82   8  60  58
33  45  92  85  44
34  62  39  38  54
35  98  80  93  16
36  37  58  40  72
37  72  22  42  38
38  45  16  52  17
39  22  15  18  37
40  48   2   2  31
41  50  78  70  40
42  60  62  69  34
43  95  58   4  70
44  20  18  66  23
45  87  45  64   6
46  39  29  60  33
47  18  59  64  59
48  65  10  86  66
49  38  76  97  79